receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 5s
    send_batch_size: 50

exporters:
  splunk_hec:
    token: "abcd1234-efgh-5678-ijkl-9012mnop3456"
    endpoint: "http://splunk:8088/services/collector"

  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]

  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, splunk_hec, elasticsearch]
